updated workflows

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -9,29 +9,35 @@ jobs:
 
         steps:
             - name: Checkout code
-              uses: actions/checkout@v2
+              uses: actions/checkout@v3
+
+            - name: Set up Node.js
+              uses: actions/setup-node@v3
+              with:
+                  node-version: "20"
+
+            - name: Set environment variable for VITE_API_URL
+              run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> $GITHUB_ENV
+
+            - name: Install dependencies
+              run: npm install
+
+            - name: Build the app
+              run: npm run build
 
             - name: Set up AWS CLI
-              uses: aws-actions/configure-aws-credentials@v1
+              uses: aws-actions/configure-aws-credentials@v2
               with:
                   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                   aws-region: ${{ secrets.AWS_REGION }}
 
-            - name: Download build artifact from another repo or specific run
-              uses: actions/download-artifact@v5
-              with:
-                  name: react-build
-                  github-token: ${{ secrets.GH_PAT }}
-                  repository: sudeepthi59o/InventoryTracker-SpringBoot-Frontend
-                  path: ./dist
-
             - name: Sync build to S3
               run: |
                   if [ -d "./dist" ]; then
-                      echo "Uploading dist/ to S3..."
-                      aws s3 sync ./dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
+                    echo "Uploading dist/ to S3..."
+                    aws s3 sync ./dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
                   else
-                      echo "dist/ directory not found. Skipping S3 sync."
-                      exit 1
+                    echo "dist/ directory not found. Skipping S3 sync."
+                    exit 1
                   fi
