trying new workflow

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -11,9 +11,6 @@ jobs:
             - name: Checkout code
               uses: actions/checkout@v2
 
-            - name: List files in current directory
-              run: ls -R
-
             - name: Set up AWS CLI
               uses: aws-actions/configure-aws-credentials@v1
               with:
@@ -25,8 +22,19 @@ jobs:
               uses: actions/download-artifact@v4
               with:
                   name: react-build
-                  path: dist/
+                  path: ./dist
+
+            - name: List contents of dist/
+              run: |
+                  echo "Listing contents of dist/ directory:"
+                  ls -R ./dist
 
             - name: Sync build to S3
               run: |
-                  aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
+                  if [ -d "./dist" ]; then
+                      echo "Uploading dist/ to S3..."
+                      aws s3 sync ./dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
+                  else
+                      echo "dist/ directory not found. Skipping S3 sync."
+                      exit 1
+                  fi
